# Generated by Django 5.2.4 on 2025-07-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0003_alter_video_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history_records', to=settings.AUTH_USER_MODEL, verbose_name='Viewed By')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_history_records', to='videos.video', verbose_name='Video Viewed')),
            ],
            options={
                'verbose_name': 'View History Record',
                'verbose_name_plural': 'View History Records',
                'ordering': ['-created'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
